domain: tools.<<team-name>>.cloud
okdDomain: test.<<team-name>>.cloud
okd_ca_common_name: "okd_ca.{{ domain }}"
bucketName: <<team-name>>-securebucket
vault:
  host: vault.{{ domain }}
  port: 8200
  cert_ttl: 8759h #must be less than when your Intermediate Certificate Authority expires
  role_name: dev_tools
  okd_role_name: test_role
  team_role_name: team
  int_ca: pki_int_<<team-name>>
  okd_ca: pki_int_okd
  project_name: "<<team-name>>"
psql:
  dbName: "<<team-name>>_db"
  dbUser: "db_user"
okd:
  username: "admin"
  admin_user: "admin"
  password: "{{ okdAdminPassword }}"
  pipeline_user: "pipeline_user"
  bucketName: <<team-name>>-securebucket
  master_name: okd
  node_name: okd-node
jdk:
  version: 8
  build: 211
