- name: Install SSM and Cloudwatch Control and Audit agents
  hosts:
    - jira-server
    - bitbucket-server
    - confluence-server
    - jenkins-server
  gather_facts: true
  become: true
  serial: 1
  tasks:
    - import_role:
        name: ssm-cloudwatch

- name: Install common tools
  hosts:
    - jira-server
    - bitbucket-server
    - confluence-server
    - vault-server
    - jenkins-server
  gather_facts: true
  become: true
  tasks:
    - import_role:
        name: common_tools

- name: Install Git
  hosts:
    - bitbucket-server
    - jenkins-server
  gather_facts: true
  become: true
  tasks:
    - import_role:
        name: git

- name: Install psql
  hosts:
    - jira-server
    - bitbucket-server
    - confluence-server
    - vault-server
  gather_facts: true
  become: true
  tasks:
    - import_role:
        name: postgresql

- name: Install and set up Vault
  hosts: vault-server
  gather_facts: true
  become: true
  tasks:
    - import_role:
        name: vault

- name: Install Jenkins
  hosts: jenkins-server
  gather_facts: true
  become: true
  tasks:
    - import_role:
        name: jenkins

- name: Install BitBucket
  hosts: bitbucket-server
  gather_facts: true
  become: true
  tasks:
    - import_role:
        name: bitbucket

- name: Install Jira
  hosts: jira-server
  gather_facts: true
  become: true
  tasks:
    - import_role:
        name: jira

- name: Install Confluence
  hosts: confluence-server
  gather_facts: true
  become: true
  tasks:
    - import_role:
        name: confluence

- name: Install Workspace tools
  hosts: workspaces
  gather_facts: true
  become: true
  tasks:
    - import_role:
        name: workspace

- name: Get certificates for all user workspaces
  hosts: localworkspace
  gather_facts: true
  become: no
  tasks:
    - import_role:
        name: workspace_crt_keys
